# Generated by Django 3.2.4 on 2024-11-17 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_mongo', '0001_initial'),
        ('orders_mongo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermongo',
            name='Price',
        ),
        migrations.RemoveField(
            model_name='ordermongo',
            name='Product',
        ),
        migrations.AddField(
            model_name='ordermongo',
            name='Product',
            field=models.ManyToManyField(related_name='orders', to='products_mongo.ProductMongo'),
        ),
    ]
