# Generated by Django 3.2.4 on 2024-11-17 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders_mongo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMongo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adress', models.JSONField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='orders_mongo.ordermongo')),
            ],
        ),
    ]
