# Generated by Django 3.2.4 on 2024-11-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('OrderId', models.AutoField(primary_key=True, serialize=False)),
                ('Products', models.JSONField()),
            ],
        ),
    ]
